Name: role.rpc
ListenOn: 0.0.0.0:8802
Mode: dev



Log:
  ServiceName: user-rpc
  Level: info
  Encoding: plain

Redis:
  Host: 0.0.0.0:6379
  Type: node

Rdb:
  - Host: 0.0.0.0:6379
    Password:
    DB: 1
    MinIdleConn: 200
    DialTimeout: 60s
    ReadTimeout: 500ms
    WriteTimeout: 500ms
    PoolSize: 100
    PoolTimeout: 240s
    EnableTrace: true

DB:
  Name: xueden_student_mangement_system
  Addr: 0.0.0.0:3306
  UserName: root
  Password: root
  ShowLog: true                   # 是否打印所有SQL日志
  MaxIdleConn: 10                 # 最大闲置的连接数，0意味着使用默认的大小2， 小于0表示不使用连接池
  MaxOpenConn: 60                 # 最大打开的连接数, 需要小于数据库配置中的max_connections数
  ConnMaxLifeTime: 4h             # 单个连接最大存活时间，建议设置比数据库超时时长(wait_timeout)稍小一些
  SlowThreshold: 0ms                # 慢查询阈值，设置后只打印慢查询日志，默认为200ms

