// Code generated by goctl. DO NOT EDIT!
// Source: student.proto

package server

import (
	"context"

	"xuedengwang/service/student/rpc/internal/logic"
	"xuedengwang/service/student/rpc/internal/svc"
	"xuedengwang/service/student/rpc/pb"
)

type StudentServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedStudentServer
}

func NewStudentServer(svcCtx *svc.ServiceContext) *StudentServer {
	return &StudentServer{
		svcCtx: svcCtx,
	}
}

func (s *StudentServer) GetStudent(ctx context.Context, in *pb.GetStudentReq) (*pb.GetStudentResp, error) {
	l := logic.NewGetStudentLogic(ctx, s.svcCtx)
	return l.GetStudent(in)
}

func (s *StudentServer) GetStudentByID(ctx context.Context, in *pb.GetStudentByIDReq) (*pb.GetStudentByIDResp, error) {
	l := logic.NewGetStudentByIDLogic(ctx, s.svcCtx)
	return l.GetStudentByID(in)
}

func (s *StudentServer) UpdateStudent(ctx context.Context, in *pb.UpdateStudentReq) (*pb.StudentInterface, error) {
	l := logic.NewUpdateStudentLogic(ctx, s.svcCtx)
	return l.UpdateStudent(in)
}

func (s *StudentServer) AddStudent(ctx context.Context, in *pb.AddStudentReq) (*pb.StudentInterface, error) {
	l := logic.NewAddStudentLogic(ctx, s.svcCtx)
	return l.AddStudent(in)
}

func (s *StudentServer) DeleteStudentByID(ctx context.Context, in *pb.DeleteStudentByIDReq) (*pb.StudentInterface, error) {
	l := logic.NewDeleteStudentByIDLogic(ctx, s.svcCtx)
	return l.DeleteStudentByID(in)
}
