// Code generated by goctl. DO NOT EDIT!
// Source: teacher.proto

package server

import (
	"context"

	"xuedengwang/service/teacher/rpc/internal/logic"
	"xuedengwang/service/teacher/rpc/internal/svc"
	"xuedengwang/service/teacher/rpc/pb"
)

type TeacherServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedTeacherServer
}

func NewTeacherServer(svcCtx *svc.ServiceContext) *TeacherServer {
	return &TeacherServer{
		svcCtx: svcCtx,
	}
}

func (s *TeacherServer) GetTeacher(ctx context.Context, in *pb.GetTeacherReq) (*pb.GetTeacherResp, error) {
	l := logic.NewGetTeacherLogic(ctx, s.svcCtx)
	return l.GetTeacher(in)
}

func (s *TeacherServer) GetTeacherByID(ctx context.Context, in *pb.GetTeacherByIDReq) (*pb.GetTeacherByIDResp, error) {
	l := logic.NewGetTeacherByIDLogic(ctx, s.svcCtx)
	return l.GetTeacherByID(in)
}

func (s *TeacherServer) UpdateTeacher(ctx context.Context, in *pb.UpdateTeacherReq) (*pb.TeacherInterface, error) {
	l := logic.NewUpdateTeacherLogic(ctx, s.svcCtx)
	return l.UpdateTeacher(in)
}

func (s *TeacherServer) AddTeacher(ctx context.Context, in *pb.AddTeacherReq) (*pb.TeacherInterface, error) {
	l := logic.NewAddTeacherLogic(ctx, s.svcCtx)
	return l.AddTeacher(in)
}

func (s *TeacherServer) DeleteTeacherByID(ctx context.Context, in *pb.DeleteTeacherByIDReq) (*pb.TeacherInterface, error) {
	l := logic.NewDeleteTeacherByIDLogic(ctx, s.svcCtx)
	return l.DeleteTeacherByID(in)
}
