// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: scores.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScoresInterface struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScoresInterface) Reset() {
	*x = ScoresInterface{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoresInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoresInterface) ProtoMessage() {}

func (x *ScoresInterface) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoresInterface.ProtoReflect.Descriptor instead.
func (*ScoresInterface) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{0}
}

type ScoresDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreateTime  string  `protobuf:"bytes,1,opt,name=createTime,proto3" json:"createTime,omitempty"`
	CreateBy    int64   `protobuf:"varint,2,opt,name=createBy,proto3" json:"createBy,omitempty"`
	UpdateTime  string  `protobuf:"bytes,3,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	UpdateBy    int64   `protobuf:"varint,4,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
	Remarks     string  `protobuf:"bytes,5,opt,name=remarks,proto3" json:"remarks,omitempty"`
	Score       float32 `protobuf:"fixed32,6,opt,name=score,proto3" json:"score,omitempty"`
	Type        string  `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Course      string  `protobuf:"bytes,8,opt,name=course,proto3" json:"course,omitempty"`
	Stuno       string  `protobuf:"bytes,9,opt,name=stuno,proto3" json:"stuno,omitempty"`
	GradeClass  string  `protobuf:"bytes,10,opt,name=gradeClass,proto3" json:"gradeClass,omitempty"`
	StudentName string  `protobuf:"bytes,11,opt,name=studentName,proto3" json:"studentName,omitempty"`
	ID          int64   `protobuf:"varint,12,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *ScoresDao) Reset() {
	*x = ScoresDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoresDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoresDao) ProtoMessage() {}

func (x *ScoresDao) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoresDao.ProtoReflect.Descriptor instead.
func (*ScoresDao) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{1}
}

func (x *ScoresDao) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *ScoresDao) GetCreateBy() int64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *ScoresDao) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *ScoresDao) GetUpdateBy() int64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

func (x *ScoresDao) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

func (x *ScoresDao) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScoresDao) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ScoresDao) GetCourse() string {
	if x != nil {
		return x.Course
	}
	return ""
}

func (x *ScoresDao) GetStuno() string {
	if x != nil {
		return x.Stuno
	}
	return ""
}

func (x *ScoresDao) GetGradeClass() string {
	if x != nil {
		return x.GradeClass
	}
	return ""
}

func (x *ScoresDao) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *ScoresDao) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type GetScoresReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageIndex    int32  `protobuf:"varint,1,opt,name=pageIndex,proto3" json:"pageIndex,omitempty"`
	PageSize     int32  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	GradeClassId int64  `protobuf:"varint,3,opt,name=gradeClassId,proto3" json:"gradeClassId,omitempty"`
	Stuno        string `protobuf:"bytes,4,opt,name=stuno,proto3" json:"stuno,omitempty"`
	StudentName  string `protobuf:"bytes,5,opt,name=studentName,proto3" json:"studentName,omitempty"`
	CourseId     int64  `protobuf:"varint,6,opt,name=courseId,proto3" json:"courseId,omitempty"`
}

func (x *GetScoresReq) Reset() {
	*x = GetScoresReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScoresReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoresReq) ProtoMessage() {}

func (x *GetScoresReq) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoresReq.ProtoReflect.Descriptor instead.
func (*GetScoresReq) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{2}
}

func (x *GetScoresReq) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *GetScoresReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetScoresReq) GetGradeClassId() int64 {
	if x != nil {
		return x.GradeClassId
	}
	return 0
}

func (x *GetScoresReq) GetStuno() string {
	if x != nil {
		return x.Stuno
	}
	return ""
}

func (x *GetScoresReq) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *GetScoresReq) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

type GetScoresResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content       []*ScoresDao `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"`
	TotalElements int64        `protobuf:"varint,2,opt,name=totalElements,proto3" json:"totalElements,omitempty"`
}

func (x *GetScoresResp) Reset() {
	*x = GetScoresResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScoresResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoresResp) ProtoMessage() {}

func (x *GetScoresResp) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoresResp.ProtoReflect.Descriptor instead.
func (*GetScoresResp) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{3}
}

func (x *GetScoresResp) GetContent() []*ScoresDao {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GetScoresResp) GetTotalElements() int64 {
	if x != nil {
		return x.TotalElements
	}
	return 0
}

type Course struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Course) Reset() {
	*x = Course{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{4}
}

func (x *Course) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Course) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Student struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Student) Reset() {
	*x = Student{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{5}
}

func (x *Student) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Student) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GradeClass struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GradeClass) Reset() {
	*x = GradeClass{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GradeClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeClass) ProtoMessage() {}

func (x *GradeClass) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeClass.ProtoReflect.Descriptor instead.
func (*GradeClass) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{6}
}

func (x *GradeClass) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GradeClass) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateScoresReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score      float32 `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	UpdateByID int64   `protobuf:"varint,8,opt,name=updateByID,proto3" json:"updateByID,omitempty"`
	ID         int64   `protobuf:"varint,7,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *UpdateScoresReq) Reset() {
	*x = UpdateScoresReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateScoresReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScoresReq) ProtoMessage() {}

func (x *UpdateScoresReq) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScoresReq.ProtoReflect.Descriptor instead.
func (*UpdateScoresReq) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateScoresReq) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *UpdateScoresReq) GetUpdateByID() int64 {
	if x != nil {
		return x.UpdateByID
	}
	return 0
}

func (x *UpdateScoresReq) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type AddScoresReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ByID         int64 `protobuf:"varint,1,opt,name=ByID,proto3" json:"ByID,omitempty"`
	CourseID     int64 `protobuf:"varint,4,opt,name=courseID,proto3" json:"courseID,omitempty"`
	GradeClassID int64 `protobuf:"varint,6,opt,name=gradeClassID,proto3" json:"gradeClassID,omitempty"`
}

func (x *AddScoresReq) Reset() {
	*x = AddScoresReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddScoresReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddScoresReq) ProtoMessage() {}

func (x *AddScoresReq) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddScoresReq.ProtoReflect.Descriptor instead.
func (*AddScoresReq) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{8}
}

func (x *AddScoresReq) GetByID() int64 {
	if x != nil {
		return x.ByID
	}
	return 0
}

func (x *AddScoresReq) GetCourseID() int64 {
	if x != nil {
		return x.CourseID
	}
	return 0
}

func (x *AddScoresReq) GetGradeClassID() int64 {
	if x != nil {
		return x.GradeClassID
	}
	return 0
}

type DeleteScoresByIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScoresID int64 `protobuf:"varint,1,opt,name=ScoresID,proto3" json:"ScoresID,omitempty"`
}

func (x *DeleteScoresByIDReq) Reset() {
	*x = DeleteScoresByIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteScoresByIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScoresByIDReq) ProtoMessage() {}

func (x *DeleteScoresByIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScoresByIDReq.ProtoReflect.Descriptor instead.
func (*DeleteScoresByIDReq) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteScoresByIDReq) GetScoresID() int64 {
	if x != nil {
		return x.ScoresID
	}
	return 0
}

type GetScoreCensusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GradeClassId int64 `protobuf:"varint,1,opt,name=gradeClassId,proto3" json:"gradeClassId,omitempty"`
	CourseId     int64 `protobuf:"varint,2,opt,name=courseId,proto3" json:"courseId,omitempty"`
}

func (x *GetScoreCensusReq) Reset() {
	*x = GetScoreCensusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScoreCensusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreCensusReq) ProtoMessage() {}

func (x *GetScoreCensusReq) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreCensusReq.ProtoReflect.Descriptor instead.
func (*GetScoreCensusReq) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{10}
}

func (x *GetScoreCensusReq) GetGradeClassId() int64 {
	if x != nil {
		return x.GradeClassId
	}
	return 0
}

func (x *GetScoreCensusReq) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

type GetScoreCensusResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Census []*Census `protobuf:"bytes,1,rep,name=census,proto3" json:"census,omitempty"`
}

func (x *GetScoreCensusResp) Reset() {
	*x = GetScoreCensusResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScoreCensusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreCensusResp) ProtoMessage() {}

func (x *GetScoreCensusResp) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreCensusResp.ProtoReflect.Descriptor instead.
func (*GetScoreCensusResp) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{11}
}

func (x *GetScoreCensusResp) GetCensus() []*Census {
	if x != nil {
		return x.Census
	}
	return nil
}

type Census struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value int64  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Census) Reset() {
	*x = Census{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Census) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Census) ProtoMessage() {}

func (x *Census) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Census.ProtoReflect.Descriptor instead.
func (*Census) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{12}
}

func (x *Census) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Census) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type DateType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []float32 `protobuf:"fixed32,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	Type string    `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DateType) Reset() {
	*x = DateType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DateType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateType) ProtoMessage() {}

func (x *DateType) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateType.ProtoReflect.Descriptor instead.
func (*DateType) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{13}
}

func (x *DateType) GetData() []float32 {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DateType) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DateType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetScoresContrastCensusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CourseId int64 `protobuf:"varint,1,opt,name=courseId,proto3" json:"courseId,omitempty"`
}

func (x *GetScoresContrastCensusReq) Reset() {
	*x = GetScoresContrastCensusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScoresContrastCensusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoresContrastCensusReq) ProtoMessage() {}

func (x *GetScoresContrastCensusReq) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoresContrastCensusReq.ProtoReflect.Descriptor instead.
func (*GetScoresContrastCensusReq) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{14}
}

func (x *GetScoresContrastCensusReq) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

type ScoresContrastCensus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CategoryList         []string    `protobuf:"bytes,1,rep,name=categoryList,proto3" json:"categoryList,omitempty"`
	BarEchartsSeriesList []*DateType `protobuf:"bytes,2,rep,name=barEchartsSeriesList,proto3" json:"barEchartsSeriesList,omitempty"`
}

func (x *ScoresContrastCensus) Reset() {
	*x = ScoresContrastCensus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoresContrastCensus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoresContrastCensus) ProtoMessage() {}

func (x *ScoresContrastCensus) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoresContrastCensus.ProtoReflect.Descriptor instead.
func (*ScoresContrastCensus) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{15}
}

func (x *ScoresContrastCensus) GetCategoryList() []string {
	if x != nil {
		return x.CategoryList
	}
	return nil
}

func (x *ScoresContrastCensus) GetBarEchartsSeriesList() []*DateType {
	if x != nil {
		return x.BarEchartsSeriesList
	}
	return nil
}

type GetScoresContrastCensusResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScoresContrastCensus *ScoresContrastCensus `protobuf:"bytes,1,opt,name=scoresContrastCensus,proto3" json:"scoresContrastCensus,omitempty"`
}

func (x *GetScoresContrastCensusResp) Reset() {
	*x = GetScoresContrastCensusResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scores_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScoresContrastCensusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoresContrastCensusResp) ProtoMessage() {}

func (x *GetScoresContrastCensusResp) ProtoReflect() protoreflect.Message {
	mi := &file_scores_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoresContrastCensusResp.ProtoReflect.Descriptor instead.
func (*GetScoresContrastCensusResp) Descriptor() ([]byte, []int) {
	return file_scores_proto_rawDescGZIP(), []int{16}
}

func (x *GetScoresContrastCensusResp) GetScoresContrastCensus() *ScoresContrastCensus {
	if x != nil {
		return x.ScoresContrastCensus
	}
	return nil
}

var File_scores_proto protoreflect.FileDescriptor

var file_scores_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x22, 0xc7, 0x02, 0x0a, 0x09, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73,
	0x44, 0x61, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x79, 0x12,
	0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x65, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65,
	0x6d, 0x61, 0x72, 0x6b, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x75, 0x6e, 0x6f,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x75, 0x6e, 0x6f, 0x12, 0x1e, 0x0a,
	0x0a, 0x67, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x67, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x20, 0x0a,
	0x0b, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x22,
	0xc0, 0x01, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x67, 0x72,
	0x61, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x67, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x75, 0x6e, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x74, 0x75, 0x6e, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74, 0x75, 0x64, 0x65,
	0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65,
	0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65,
	0x49, 0x64, 0x22, 0x5e, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x27, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73,
	0x44, 0x61, 0x6f, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0d,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x22, 0x2c, 0x0a, 0x06, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x2d, 0x0a, 0x07, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x30, 0x0a, 0x0a, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x57, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x42, 0x79, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x79, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x22, 0x62, 0x0a, 0x0c, 0x41, 0x64,
	0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x79,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x42, 0x79, 0x49, 0x44, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x67, 0x72,
	0x61, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x67, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x44, 0x22, 0x31,
	0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x42, 0x79,
	0x49, 0x44, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x49,
	0x44, 0x22, 0x53, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x43, 0x65, 0x6e,
	0x73, 0x75, 0x73, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x0c, 0x67, 0x72, 0x61, 0x64, 0x65, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x67, 0x72,
	0x61, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f,
	0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6f,
	0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x22, 0x38, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x43, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x06,
	0x63, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x52, 0x06, 0x63, 0x65, 0x6e, 0x73, 0x75, 0x73,
	0x22, 0x32, 0x0a, 0x06, 0x43, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x46, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x38, 0x0a, 0x1a,
	0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73,
	0x74, 0x43, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f,
	0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6f,
	0x75, 0x72, 0x73, 0x65, 0x49, 0x64, 0x22, 0x7c, 0x0a, 0x14, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x43, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x12, 0x22,
	0x0a, 0x0c, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x40, 0x0a, 0x14, 0x62, 0x61, 0x72, 0x45, 0x63, 0x68, 0x61, 0x72, 0x74, 0x73,
	0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x14,
	0x62, 0x61, 0x72, 0x45, 0x63, 0x68, 0x61, 0x72, 0x74, 0x73, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x6b, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x73, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x43, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x4c, 0x0a, 0x14, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x73, 0x74, 0x43, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x73, 0x74, 0x43, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x52, 0x14, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x73, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x43, 0x65, 0x6e, 0x73, 0x75,
	0x73, 0x32, 0x86, 0x03, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x67,
	0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x38, 0x0a,
	0x0c, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x13, 0x2e,
	0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x73, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x73, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x10, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x42, 0x79, 0x49, 0x44, 0x12,
	0x17, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x73, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x73, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x3f, 0x0a,
	0x0e, 0x67, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x43, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x12,
	0x15, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x43, 0x65, 0x6e,
	0x73, 0x75, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x43, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x5a,
	0x0a, 0x17, 0x67, 0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x73, 0x74, 0x43, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x12, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74,
	0x43, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74,
	0x43, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_scores_proto_rawDescOnce sync.Once
	file_scores_proto_rawDescData = file_scores_proto_rawDesc
)

func file_scores_proto_rawDescGZIP() []byte {
	file_scores_proto_rawDescOnce.Do(func() {
		file_scores_proto_rawDescData = protoimpl.X.CompressGZIP(file_scores_proto_rawDescData)
	})
	return file_scores_proto_rawDescData
}

var file_scores_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_scores_proto_goTypes = []interface{}{
	(*ScoresInterface)(nil),             // 0: pb.ScoresInterface
	(*ScoresDao)(nil),                   // 1: pb.ScoresDao
	(*GetScoresReq)(nil),                // 2: pb.GetScoresReq
	(*GetScoresResp)(nil),               // 3: pb.GetScoresResp
	(*Course)(nil),                      // 4: pb.Course
	(*Student)(nil),                     // 5: pb.Student
	(*GradeClass)(nil),                  // 6: pb.GradeClass
	(*UpdateScoresReq)(nil),             // 7: pb.UpdateScoresReq
	(*AddScoresReq)(nil),                // 8: pb.AddScoresReq
	(*DeleteScoresByIDReq)(nil),         // 9: pb.DeleteScoresByIDReq
	(*GetScoreCensusReq)(nil),           // 10: pb.GetScoreCensusReq
	(*GetScoreCensusResp)(nil),          // 11: pb.GetScoreCensusResp
	(*Census)(nil),                      // 12: pb.Census
	(*DateType)(nil),                    // 13: pb.DateType
	(*GetScoresContrastCensusReq)(nil),  // 14: pb.GetScoresContrastCensusReq
	(*ScoresContrastCensus)(nil),        // 15: pb.ScoresContrastCensus
	(*GetScoresContrastCensusResp)(nil), // 16: pb.GetScoresContrastCensusResp
}
var file_scores_proto_depIdxs = []int32{
	1,  // 0: pb.GetScoresResp.content:type_name -> pb.ScoresDao
	12, // 1: pb.GetScoreCensusResp.census:type_name -> pb.Census
	13, // 2: pb.ScoresContrastCensus.barEchartsSeriesList:type_name -> pb.DateType
	15, // 3: pb.GetScoresContrastCensusResp.scoresContrastCensus:type_name -> pb.ScoresContrastCensus
	2,  // 4: pb.Score.getScores:input_type -> pb.GetScoresReq
	7,  // 5: pb.Score.updateScores:input_type -> pb.UpdateScoresReq
	8,  // 6: pb.Score.addScores:input_type -> pb.AddScoresReq
	9,  // 7: pb.Score.deleteScoresByID:input_type -> pb.DeleteScoresByIDReq
	10, // 8: pb.Score.getScoreCensus:input_type -> pb.GetScoreCensusReq
	14, // 9: pb.Score.getScoresContrastCensus:input_type -> pb.GetScoresContrastCensusReq
	3,  // 10: pb.Score.getScores:output_type -> pb.GetScoresResp
	0,  // 11: pb.Score.updateScores:output_type -> pb.ScoresInterface
	0,  // 12: pb.Score.addScores:output_type -> pb.ScoresInterface
	0,  // 13: pb.Score.deleteScoresByID:output_type -> pb.ScoresInterface
	11, // 14: pb.Score.getScoreCensus:output_type -> pb.GetScoreCensusResp
	16, // 15: pb.Score.getScoresContrastCensus:output_type -> pb.GetScoresContrastCensusResp
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_scores_proto_init() }
func file_scores_proto_init() {
	if File_scores_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_scores_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoresInterface); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoresDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScoresReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScoresResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Course); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Student); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GradeClass); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateScoresReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddScoresReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteScoresByIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScoreCensusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScoreCensusResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Census); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DateType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScoresContrastCensusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoresContrastCensus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scores_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScoresContrastCensusResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scores_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scores_proto_goTypes,
		DependencyIndexes: file_scores_proto_depIdxs,
		MessageInfos:      file_scores_proto_msgTypes,
	}.Build()
	File_scores_proto = out.File
	file_scores_proto_rawDesc = nil
	file_scores_proto_goTypes = nil
	file_scores_proto_depIdxs = nil
}
