// Code generated by goctl. DO NOT EDIT.
package types

type Interface struct {
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Role       Role   `json:"role"`
	CreateTime string `json:"createTime"`
	Sex        string `json:"sex"`
	UserIcon   string `json:"userIcon"`
	Username   string `json:"username"`
	Email      string `json:"email"`
	Realname   string `json:"realname"`
	Token      string `json:"token"`
}

type DateTypeName struct {
	Data []float32 `json:"data"`
	Type string    `json:"type"`
	Name string    `json:"name"`
}

type Scores struct {
	CategoryList         []string        `json:"categoryList"`
	BarEchartsSeriesList []*DateTypeName `json:"barEchartsSeriesList"`
}

type HomeResp struct {
	TeacherNums int64  `json:"teacherNums"`
	Scores      Scores `json:"scores"`
	StudentNums int64  `json:"studentNums"`
	ClassNums   int64  `json:"classNums"`
	CourseNums  int64  `json:"courseNums"`
}

type UserIconResp struct {
	UserIcon string `json:"userIcon"`
}

type UpdateInfoReq struct {
	Realname string `json:"realname"`
	Sex      string `json:"sex"`
	UserIcon string `json:"userIcon"`
}

type UpdatePwdReq struct {
	NewPass  string `json:"newPass"`
	UsedPass string `json:"usedPass"`
}

type SendEmailReq struct {
	Email string `form:"email,optional"`
}

type VerifyCodeReq struct {
	Code string `form:"code"`
}

type UpdateEmailReq struct {
	Email string `form:"email"`
	Code  string `form:"code"`
}

type GetUserReq struct {
	PageIndex   int32  `form:"pageIndex"`
	PageSize    int32  `form:"pageSize"`
	SearchValue string `form:"searchValue,optional"`
	Status      string `form:"status,optional"`
}

type User struct {
	CreateTime string `json:"createTime"`
	CreateBy   int64  `json:"createBy"`
	UpdateTime string `json:"updateTime"`
	UpdateBy   int64  `json:"updateBy"`
	Remarks    string `json:"remarks"`
	ID         int64  `json:"id"`
	Password   string `json:"password"`
	Username   string `json:"username"`
	Realname   string `json:"realname"`
	Sex        string `json:"sex"`
	Status     int32  `json:"status"`
	Email      string `json:"email"`
	UserIcon   string `json:"userIcon"`
	SysRole    Role   `json:"sysRole"`
}

type GetUserResp struct {
	Content       []*User `json:"content"`
	TotalElements int64   `json:"totalElements"`
}

type UpdateUserReq struct {
	Remarks   string `json:"remarks"`
	ID        int64  `json:"id"`
	Password  string `json:"password"`
	Username  string `json:"username"`
	Realname  string `json:"realname"`
	Sex       string `json:"sex"`
	Status    int32  `json:"status"`
	Email     string `json:"email"`
	SysRoleID int64  `json:"sysRoleId"`
}

type AddUserReq struct {
	Remarks   string `json:"remarks"`
	Password  string `json:"password"`
	Username  string `json:"username"`
	Realname  string `json:"realname"`
	Sex       string `json:"sex"`
	Status    int32  `json:"status"`
	Email     string `json:"email"`
	SysRoleID int64  `json:"sysRoleId"`
}

type GetUserByIDReq struct {
	ID int64 `path:"id"`
}

type GetUserByIDResp struct {
	CreateTime string `json:"createTime"`
	CreateBy   int64  `json:"createBy"`
	UpdateTime string `json:"updateTime"`
	UpdateBy   int64  `json:"updateBy"`
	Remarks    string `json:"remarks"`
	ID         int64  `json:"id"`
	Password   string `json:"password"`
	Username   string `json:"username"`
	Realname   string `json:"realname"`
	Sex        string `json:"sex"`
	Status     int32  `json:"status"`
	Email      string `json:"email"`
	UserIcon   string `json:"userIcon"`
	SysRoleID  int64  `json:"sysRoleId"`
}

type DeleteUserByIDReq struct {
	ID int64 `path:"id"`
}

type Role struct {
	CreateTime string `json:"createTime"`
	CreateBy   int64  `json:"createBy"`
	UpdateTime string `json:"updateTime"`
	UpdateBy   int64  `json:"updateBy"`
	Remarks    string `json:"remarks"`
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Code       string `json:"code"`
}

type RoleAllResp struct {
	RoleAll []*RoleAll `json:"roleAll"`
}

type RoleAll struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type GetRoleReq struct {
	PageIndex   int32  `form:"pageIndex"`
	PageSize    int32  `form:"pageSize"`
	SearchValue string `form:"searchValue,optional"`
}

type GetRoleResp struct {
	Content       []*Role `json:"content"`
	TotalElements int64   `json:"totalElements"`
}

type GetRoleByIDReq struct {
	ID int64 `path:"id"`
}

type GetRoleByIDResp struct {
	CreateTime string `json:"createTime"`
	CreateBy   int64  `json:"createBy"`
	UpdateTime string `json:"updateTime"`
	UpdateBy   int64  `json:"updateBy"`
	Remarks    string `json:"remarks"`
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Code       string `json:"code"`
}

type UpdateRoleReq struct {
	Code    string `json:"code"`
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Remarks string `json:"remarks"`
}

type AddRoleReq struct {
	Code    string `json:"code"`
	Name    string `json:"name"`
	Remarks string `json:"remarks"`
}

type DeleteRoleByIDReq struct {
	ID int64 `path:"id"`
}

type Student struct {
	CreateTime     string `json:"createTime"`
	CreateBy       int64  `json:"createBy"`
	UpdateTime     string `json:"updateTime"`
	UpdateBy       int64  `json:"updateBy"`
	Remarks        string `json:"remarks"`
	ID             int64  `json:"id"`
	Name           string `json:"name"`
	Stuno          string `json:"stuno"`
	Sex            string `json:"sex"`
	Phone          string `json:"phone"`
	QQ             string `json:"qq"`
	GradeClassName string `json:"gradeClassName"`
}

type GetStudentReq struct {
	PageIndex   int32  `form:"pageIndex"`
	PageSize    int32  `form:"pageSize"`
	SearchValue string `form:"searchValue,optional"`
}

type GetStudentResp struct {
	Content       []*Student `json:"content"`
	TotalElements int64      `json:"totalElements"`
}

type GetStudentByIDReq struct {
	ID int64 `path:"id"`
}

type GetStudentByIDResp struct {
	CreateTime   string `json:"createTime"`
	CreateBy     int64  `json:"createBy"`
	UpdateTime   string `json:"updateTime"`
	UpdateBy     int64  `json:"updateBy"`
	Remarks      string `json:"remarks"`
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	Stuno        string `json:"stuno"`
	Sex          string `json:"sex"`
	Phone        string `json:"phone"`
	QQ           string `json:"qq"`
	GradeClassID int64  `json:"gradeClassId"`
}

type UpdateStudentReq struct {
	Remarks      string `json:"remarks"`
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	Stuno        string `json:"stuno"`
	Sex          string `json:"sex"`
	Phone        string `json:"phone"`
	QQ           string `json:"qq"`
	GradeClassId int64  `json:"gradeClassId"`
}

type AddStudentReq struct {
	Remarks      string `json:"remarks"`
	Name         string `json:"name"`
	Stuno        string `json:"stuno"`
	Sex          string `json:"sex"`
	Phone        string `json:"phone"`
	QQ           string `json:"qq"`
	GradeClassID int64  `json:"gradeClassId"`
}

type DeleteStudentByIDReq struct {
	ID int64 `path:"id"`
}

type Course struct {
	CreateTime string `json:"createTime"`
	CreateBy   int64  `json:"createBy"`
	UpdateTime string `json:"updateTime"`
	UpdateBy   int64  `json:"updateBy"`
	Coursename string `json:"coursename"`
	Courseno   string `json:"courseno"`
	ID         int64  `json:"id"`
	Remarks    string `json:"remarks"`
}

type CourseAllResp struct {
	CourseAll []*CourseAll `json:"courseAll"`
}

type CourseAll struct {
	ID   int64  `json:"id"`
	Name string `json:"name,optional"`
}

type GetCourseReq struct {
	PageIndex   int32  `form:"pageIndex"`
	PageSize    int32  `form:"pageSize"`
	SearchValue string `form:"searchValue,optional"`
}

type GetCourseResp struct {
	Content       []*Course `json:"content"`
	TotalElements int64     `json:"totalElements"`
}

type GetCourseByIDReq struct {
	ID int64 `path:"id"`
}

type GetCourseByIDResp struct {
	CreateTime string `json:"createTime"`
	CreateBy   int64  `json:"createBy"`
	UpdateTime string `json:"updateTime"`
	UpdateBy   int64  `json:"updateBy"`
	Coursename string `json:"coursename"`
	Courseno   string `json:"courseno"`
	ID         int64  `json:"id"`
	Remarks    string `json:"remarks"`
}

type UpdateCourseReq struct {
	Coursename string `json:"coursename"`
	Courseno   string `json:"courseno"`
	ID         int64  `json:"id"`
	Remarks    string `json:"remarks"`
}

type AddCourseReq struct {
	Coursename string `json:"coursename"`
	Courseno   string `json:"courseno"`
	Remarks    string `json:"remarks"`
}

type DeleteCourseByIDReq struct {
	ID int64 `path:"id"`
}

type Teacher struct {
	CreateTime string `json:"createTime"`
	CreateBy   int64  `json:"createBy"`
	UpdateTime string `json:"updateTime"`
	UpdateBy   int64  `json:"updateBy"`
	Remarks    string `json:"remarks"`
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Teachno    string `json:"teachno"`
	Sex        string `json:"sex"`
	Phone      string `json:"phone"`
	QQ         string `json:"qq"`
	CourseName string `json:"courseName"`
}

type GetTeacherReq struct {
	PageIndex   int32  `form:"pageIndex"`
	PageSize    int32  `form:"pageSize"`
	SearchValue string `form:"searchValue,optional"`
}

type GetTeacherResp struct {
	Content       []*Teacher `json:"content"`
	TotalElements int64      `json:"totalElements"`
}

type GetTeacherByIDReq struct {
	ID int64 `path:"id"`
}

type GetTeacherByIDResp struct {
	CreateTime string `json:"createTime"`
	CreateBy   int64  `json:"createBy"`
	UpdateTime string `json:"updateTime"`
	UpdateBy   int64  `json:"updateBy"`
	Remarks    string `json:"remarks"`
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Teachno    string `json:"teachno"`
	Sex        string `json:"sex"`
	Phone      string `json:"phone"`
	QQ         string `json:"qq"`
	CourseID   int64  `json:"courseId"`
}

type UpdateTeacherReq struct {
	Remarks  string `json:"remarks"`
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Teachno  string `json:"teachno"`
	Sex      string `json:"sex"`
	Phone    string `json:"phone"`
	QQ       string `json:"qq"`
	CourseID int64  `json:"courseId"`
}

type AddTeacherReq struct {
	Remarks  string `json:"remarks"`
	Name     string `json:"name"`
	Teachno  string `json:"teachno"`
	Sex      string `json:"sex"`
	Phone    string `json:"phone"`
	QQ       string `json:"qq"`
	CourseID int64  `json:"courseId"`
}

type DeleteTeacherByIDReq struct {
	ID int64 `path:"id"`
}

type GradeClass struct {
	CreateTime string `json:"createTime"`
	CreateBy   int64  `json:"createBy"`
	UpdateTime string `json:"updateTime"`
	UpdateBy   int64  `json:"updateBy"`
	Remarks    string `json:"remarks"`
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Code       string `json:"code"`
	Grade      int32  `json:"grade"`
	Clazz      int32  `json:"clazz"`
	Students   int64  `json:"students"`
}

type GradeClassAllResp struct {
	GradeClassAll []*GradeClassAll `json:"gradeClassAll"`
}

type GradeClassAll struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type GetGradeClassReq struct {
	PageIndex   int32  `form:"pageIndex"`
	PageSize    int32  `form:"pageSize"`
	SearchValue string `form:"searchValue,optional"`
}

type GetGradeClassResp struct {
	Content       []*GradeClass `json:"content"`
	TotalElements int64         `json:"totalElements"`
}

type GetGradeClassByIDReq struct {
	ID int64 `path:"id"`
}

type GetGradeClassByIDResp struct {
	CreateTime string `json:"createTime"`
	CreateBy   int64  `json:"createBy"`
	UpdateTime string `json:"updateTime"`
	UpdateBy   int64  `json:"updateBy"`
	Remarks    string `json:"remarks"`
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Code       string `json:"code"`
	Grade      int32  `json:"grade"`
	Clazz      int32  `json:"clazz"`
	Students   int64  `json:"students"`
}

type UpdateGradeClassReq struct {
	Code    string `json:"code"`
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Remarks string `json:"remarks"`
	Grade   int32  `json:"grade"`
	Clazz   int32  `json:"clazz"`
}

type AddGradeClassReq struct {
	Code    string `json:"code"`
	Name    string `json:"name"`
	Remarks string `json:"remarks"`
	Grade   int32  `json:"grade"`
	Clazz   int32  `json:"clazz"`
}

type DeleteGradeClassByIDReq struct {
	ID int64 `path:"id"`
}

type Score struct {
	CreateTime  string  `json:"createTime"`
	CreateBy    int64   `json:"createBy"`
	UpdateTime  string  `json:"updateTime"`
	UpdateBy    int64   `json:"updateBy"`
	Remarks     string  `json:"remarks"`
	ID          int64   `json:"id"`
	Score       float32 `json:"score"`
	Type        string  `json:"type"`
	Course      string  `json:"course"`
	StudentName string  `json:"studentName"`
	Stuno       string  `json:"stuno"`
	GradeClass  string  `json:"gradeClass"`
}

type GetScoresReq struct {
	PageIndex    int32  `form:"pageIndex"`
	PageSize     int32  `form:"pageSize"`
	GradeClassId int64  `form:"gradeClassId,optional"`
	Stuno        string `form:"stuno,optional"`
	Name         string `form:"name,optional"`
	CourseId     int64  `form:"courseId,optional"`
}

type GetScoresResp struct {
	Content       []*Score `json:"content"`
	TotalElements int64    `json:"totalElements"`
}

type UpdateScoresReq struct {
	ID    int64  `json:"id"`
	Score string `json:"score"`
}

type AddScoresReq struct {
	CourseID     int64 `json:"courseId"`
	GradeClassID int64 `json:"gradeClassId"`
}

type DeleteScoresByIDReq struct {
	ID int64 `path:"id"`
}

type GetScoreCensusReq struct {
	GradeClassId int64 `form:"gradeClassId,optional"`
	CourseId     int64 `form:"courseId,optional"`
}

type GetScoreCensusResp struct {
	Census []*GetScoreCensus `json:"census"`
}

type GetScoreCensus struct {
	Name  string `json:"name"`
	Value int64  `json:"value"`
}

type GetScoresContrastCensusReq struct {
	CourseId int64 `form:"courseId"`
}

type GetScoresContrastCensusResp struct {
	Scores Scores `json:"scores"`
}
