// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCourse = "s_course"

// Course mapped from table <s_course>
type Course struct {
	ID         int64      `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id"`
	CreateBy   int64      `gorm:"column:create_by;type:bigint(20);not null" json:"create_by"`
	CreateTime *time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 创建时间
	Remarks    string     `gorm:"column:remarks;type:varchar(255);not null" json:"remarks"`
	UpdateBy   int64      `gorm:"column:update_by;type:bigint(20);not null" json:"update_by"`
	UpdateTime *time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_time"` // 更新时间
	CourseName string     `gorm:"column:course_name;type:varchar(255);not null" json:"course_name"`
	CourseNo   string     `gorm:"column:course_no;type:varchar(255);not null" json:"course_no"`
}

// TableName Course's table name
func (*Course) TableName() string {
	return TableNameCourse
}
