// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStudentScore = "s_student_score"

// StudentScore mapped from table <s_student_score>
type StudentScore struct {
	ID           int64      `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id"`
	CreateBy     int64      `gorm:"column:create_by;type:bigint(20);not null" json:"create_by"`
	CreateTime   *time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 创建时间
	Remarks      string     `gorm:"column:remarks;type:varchar(255);not null" json:"remarks"`
	UpdateBy     int64      `gorm:"column:update_by;type:bigint(20);not null" json:"update_by"`
	UpdateTime   *time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_time"` // 更新时间
	Score        float32    `gorm:"column:score;type:float;not null" json:"score"`
	Type         string     `gorm:"column:type;type:varchar(255);not null" json:"type"`
	CourseID     int64      `gorm:"column:course_id;type:bigint(20);not null;index:FKrm1fvg0dausplxq9nphxb47j9,priority:1" json:"course_id"`
	StudentID    int64      `gorm:"column:student_id;type:bigint(20);not null;index:FKfb1pcum4u0xlbod236kmngx4f,priority:1" json:"student_id"`
	GradeClassID int64      `gorm:"column:grade_class_id;type:bigint(20);not null;index:FK8mac4aaiivjtr0kd4kpyt4vm5,priority:1" json:"grade_class_id"`
	GradeClass   GradeClass `gorm:"foreignKey:GradeClassID" json:"grade_class"`
	Student      Student    `gorm:"foreignKey:StudentID" json:"student"`
	Course       Course     `gorm:"foreignKey:CourseID" json:"course"`
}

// TableName StudentScore's table name
func (*StudentScore) TableName() string {
	return TableNameStudentScore
}
