// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStudent = "s_student"

// Student mapped from table <s_student>
type Student struct {
	ID           int64      `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id"`
	CreateBy     int64      `gorm:"column:create_by;type:bigint(20);not null" json:"create_by"`
	CreateTime   *time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 创建时间
	Remarks      string     `gorm:"column:remarks;type:varchar(255);not null" json:"remarks"`
	UpdateBy     int64      `gorm:"column:update_by;type:bigint(20);not null" json:"update_by"`
	UpdateTime   *time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_time"` // 更新时间
	Name         string     `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Phone        string     `gorm:"column:phone;type:varchar(255);not null" json:"phone"`
	Qq           string     `gorm:"column:qq;type:varchar(255);not null" json:"qq"`
	Sex          string     `gorm:"column:sex;type:varchar(255);not null" json:"sex"`
	Stuno        string     `gorm:"column:stuno;type:varchar(255);not null" json:"stuno"`
	GradeClassID int64      `gorm:"column:grade_class_id;type:bigint(20);not null;index:FK8mac4aaiivjtr0kd4kpyt4vm5,priority:1" json:"grade_class_id"`
	GradeClass   GradeClass `gorm:"foreignKey:GradeClassID" json:"grade_class"`
}

// TableName Student's table name
func (*Student) TableName() string {
	return TableNameStudent
}
