// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "sys_user"

// User mapped from table <sys_user>
type User struct {
	ID         int64      `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id"`
	CreateBy   int64      `gorm:"column:create_by;type:bigint(20);not null" json:"create_by"`
	CreateTime *time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 创建时间
	Remarks    string     `gorm:"column:remarks;type:varchar(255);not null" json:"remarks"`
	UpdateBy   int64      `gorm:"column:update_by;type:bigint(20);not null" json:"update_by"`
	UpdateTime *time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_time"` // 更新时间
	Password   string     `gorm:"column:password;type:varchar(255);not null" json:"password"`
	Realname   string     `gorm:"column:realname;type:varchar(255);not null" json:"realname"`
	Sex        string     `gorm:"column:sex;type:varchar(255);not null" json:"sex"`
	Status     int32      `gorm:"column:status;type:int(11);not null" json:"status"`
	Username   string     `gorm:"column:username;type:varchar(255);not null" json:"username"`
	Email      string     `gorm:"column:email;type:varchar(255);not null" json:"email"`
	UserIcon   *string    `gorm:"column:user_icon;type:varchar(255)" json:"user_icon"`
	RoleID     int64      `gorm:"column:role_id;type:bigint(20);not null;index:FK4dm5kxn3potpfgdigehw7pdyu,priority:1" json:"role_id"`
	Role       Role       `gorm:"foreignKey:RoleID" json:"role"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
