// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: gradeclass.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GradeClassInterface struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GradeClassInterface) Reset() {
	*x = GradeClassInterface{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gradeclass_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GradeClassInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeClassInterface) ProtoMessage() {}

func (x *GradeClassInterface) ProtoReflect() protoreflect.Message {
	mi := &file_gradeclass_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeClassInterface.ProtoReflect.Descriptor instead.
func (*GradeClassInterface) Descriptor() ([]byte, []int) {
	return file_gradeclass_proto_rawDescGZIP(), []int{0}
}

type GradeClassDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreateTime string `protobuf:"bytes,1,opt,name=createTime,proto3" json:"createTime,omitempty"`
	CreateBy   int64  `protobuf:"varint,2,opt,name=createBy,proto3" json:"createBy,omitempty"`
	UpdateTime string `protobuf:"bytes,3,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	UpdateBy   int64  `protobuf:"varint,4,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
	Remarks    string `protobuf:"bytes,5,opt,name=remarks,proto3" json:"remarks,omitempty"`
	ID         int64  `protobuf:"varint,6,opt,name=ID,proto3" json:"ID,omitempty"`
	Name       string `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Code       string `protobuf:"bytes,8,opt,name=code,proto3" json:"code,omitempty"`
	Grade      int32  `protobuf:"varint,9,opt,name=grade,proto3" json:"grade,omitempty"`
	Clazz      int32  `protobuf:"varint,10,opt,name=clazz,proto3" json:"clazz,omitempty"`
	Students   int64  `protobuf:"varint,11,opt,name=students,proto3" json:"students,omitempty"`
}

func (x *GradeClassDao) Reset() {
	*x = GradeClassDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gradeclass_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GradeClassDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeClassDao) ProtoMessage() {}

func (x *GradeClassDao) ProtoReflect() protoreflect.Message {
	mi := &file_gradeclass_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeClassDao.ProtoReflect.Descriptor instead.
func (*GradeClassDao) Descriptor() ([]byte, []int) {
	return file_gradeclass_proto_rawDescGZIP(), []int{1}
}

func (x *GradeClassDao) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *GradeClassDao) GetCreateBy() int64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *GradeClassDao) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *GradeClassDao) GetUpdateBy() int64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

func (x *GradeClassDao) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

func (x *GradeClassDao) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GradeClassDao) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GradeClassDao) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GradeClassDao) GetGrade() int32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *GradeClassDao) GetClazz() int32 {
	if x != nil {
		return x.Clazz
	}
	return 0
}

func (x *GradeClassDao) GetStudents() int64 {
	if x != nil {
		return x.Students
	}
	return 0
}

type GetGradeClassReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageIndex   int32  `protobuf:"varint,1,opt,name=pageIndex,proto3" json:"pageIndex,omitempty"`
	PageSize    int32  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	SearchValue string `protobuf:"bytes,3,opt,name=searchValue,proto3" json:"searchValue,omitempty"`
}

func (x *GetGradeClassReq) Reset() {
	*x = GetGradeClassReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gradeclass_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGradeClassReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradeClassReq) ProtoMessage() {}

func (x *GetGradeClassReq) ProtoReflect() protoreflect.Message {
	mi := &file_gradeclass_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradeClassReq.ProtoReflect.Descriptor instead.
func (*GetGradeClassReq) Descriptor() ([]byte, []int) {
	return file_gradeclass_proto_rawDescGZIP(), []int{2}
}

func (x *GetGradeClassReq) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *GetGradeClassReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetGradeClassReq) GetSearchValue() string {
	if x != nil {
		return x.SearchValue
	}
	return ""
}

type GetGradeClassResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content       []*GradeClassDao `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"`
	TotalElements int64            `protobuf:"varint,2,opt,name=totalElements,proto3" json:"totalElements,omitempty"`
}

func (x *GetGradeClassResp) Reset() {
	*x = GetGradeClassResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gradeclass_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGradeClassResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradeClassResp) ProtoMessage() {}

func (x *GetGradeClassResp) ProtoReflect() protoreflect.Message {
	mi := &file_gradeclass_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradeClassResp.ProtoReflect.Descriptor instead.
func (*GetGradeClassResp) Descriptor() ([]byte, []int) {
	return file_gradeclass_proto_rawDescGZIP(), []int{3}
}

func (x *GetGradeClassResp) GetContent() []*GradeClassDao {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GetGradeClassResp) GetTotalElements() int64 {
	if x != nil {
		return x.TotalElements
	}
	return 0
}

type GetGradeClassByIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetGradeClassByIDReq) Reset() {
	*x = GetGradeClassByIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gradeclass_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGradeClassByIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradeClassByIDReq) ProtoMessage() {}

func (x *GetGradeClassByIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_gradeclass_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradeClassByIDReq.ProtoReflect.Descriptor instead.
func (*GetGradeClassByIDReq) Descriptor() ([]byte, []int) {
	return file_gradeclass_proto_rawDescGZIP(), []int{4}
}

func (x *GetGradeClassByIDReq) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type GetGradeClassByIDResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreateTime string `protobuf:"bytes,1,opt,name=createTime,proto3" json:"createTime,omitempty"`
	CreateBy   int64  `protobuf:"varint,2,opt,name=createBy,proto3" json:"createBy,omitempty"`
	UpdateTime string `protobuf:"bytes,3,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	UpdateBy   int64  `protobuf:"varint,4,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
	Remarks    string `protobuf:"bytes,5,opt,name=remarks,proto3" json:"remarks,omitempty"`
	ID         int64  `protobuf:"varint,6,opt,name=ID,proto3" json:"ID,omitempty"`
	Name       string `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Code       string `protobuf:"bytes,8,opt,name=code,proto3" json:"code,omitempty"`
	Grade      int32  `protobuf:"varint,9,opt,name=grade,proto3" json:"grade,omitempty"`
	Clazz      int32  `protobuf:"varint,10,opt,name=clazz,proto3" json:"clazz,omitempty"`
	Students   int64  `protobuf:"varint,11,opt,name=students,proto3" json:"students,omitempty"`
}

func (x *GetGradeClassByIDResp) Reset() {
	*x = GetGradeClassByIDResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gradeclass_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGradeClassByIDResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradeClassByIDResp) ProtoMessage() {}

func (x *GetGradeClassByIDResp) ProtoReflect() protoreflect.Message {
	mi := &file_gradeclass_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradeClassByIDResp.ProtoReflect.Descriptor instead.
func (*GetGradeClassByIDResp) Descriptor() ([]byte, []int) {
	return file_gradeclass_proto_rawDescGZIP(), []int{5}
}

func (x *GetGradeClassByIDResp) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *GetGradeClassByIDResp) GetCreateBy() int64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *GetGradeClassByIDResp) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *GetGradeClassByIDResp) GetUpdateBy() int64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

func (x *GetGradeClassByIDResp) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

func (x *GetGradeClassByIDResp) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GetGradeClassByIDResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetGradeClassByIDResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetGradeClassByIDResp) GetGrade() int32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *GetGradeClassByIDResp) GetClazz() int32 {
	if x != nil {
		return x.Clazz
	}
	return 0
}

func (x *GetGradeClassByIDResp) GetStudents() int64 {
	if x != nil {
		return x.Students
	}
	return 0
}

type UpdateGradeClassReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Remarks    string `protobuf:"bytes,1,opt,name=remarks,proto3" json:"remarks,omitempty"`
	ID         int64  `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	Code       string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Grade      int32  `protobuf:"varint,4,opt,name=grade,proto3" json:"grade,omitempty"`
	Clazz      int32  `protobuf:"varint,5,opt,name=clazz,proto3" json:"clazz,omitempty"`
	Name       string `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	UpdateByID int64  `protobuf:"varint,8,opt,name=updateByID,proto3" json:"updateByID,omitempty"`
}

func (x *UpdateGradeClassReq) Reset() {
	*x = UpdateGradeClassReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gradeclass_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGradeClassReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGradeClassReq) ProtoMessage() {}

func (x *UpdateGradeClassReq) ProtoReflect() protoreflect.Message {
	mi := &file_gradeclass_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGradeClassReq.ProtoReflect.Descriptor instead.
func (*UpdateGradeClassReq) Descriptor() ([]byte, []int) {
	return file_gradeclass_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateGradeClassReq) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

func (x *UpdateGradeClassReq) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *UpdateGradeClassReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateGradeClassReq) GetGrade() int32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *UpdateGradeClassReq) GetClazz() int32 {
	if x != nil {
		return x.Clazz
	}
	return 0
}

func (x *UpdateGradeClassReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGradeClassReq) GetUpdateByID() int64 {
	if x != nil {
		return x.UpdateByID
	}
	return 0
}

type AddGradeClassReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Remarks string `protobuf:"bytes,1,opt,name=remarks,proto3" json:"remarks,omitempty"`
	Code    string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Grade   int32  `protobuf:"varint,4,opt,name=grade,proto3" json:"grade,omitempty"`
	Clazz   int32  `protobuf:"varint,5,opt,name=clazz,proto3" json:"clazz,omitempty"`
	Name    string `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	ByID    int64  `protobuf:"varint,2,opt,name=byID,proto3" json:"byID,omitempty"`
}

func (x *AddGradeClassReq) Reset() {
	*x = AddGradeClassReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gradeclass_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGradeClassReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGradeClassReq) ProtoMessage() {}

func (x *AddGradeClassReq) ProtoReflect() protoreflect.Message {
	mi := &file_gradeclass_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGradeClassReq.ProtoReflect.Descriptor instead.
func (*AddGradeClassReq) Descriptor() ([]byte, []int) {
	return file_gradeclass_proto_rawDescGZIP(), []int{7}
}

func (x *AddGradeClassReq) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

func (x *AddGradeClassReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AddGradeClassReq) GetGrade() int32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *AddGradeClassReq) GetClazz() int32 {
	if x != nil {
		return x.Clazz
	}
	return 0
}

func (x *AddGradeClassReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddGradeClassReq) GetByID() int64 {
	if x != nil {
		return x.ByID
	}
	return 0
}

type DeleteGradeClassByIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GradeClassID int64 `protobuf:"varint,1,opt,name=gradeClassID,proto3" json:"gradeClassID,omitempty"`
}

func (x *DeleteGradeClassByIDReq) Reset() {
	*x = DeleteGradeClassByIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gradeclass_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGradeClassByIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGradeClassByIDReq) ProtoMessage() {}

func (x *DeleteGradeClassByIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_gradeclass_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGradeClassByIDReq.ProtoReflect.Descriptor instead.
func (*DeleteGradeClassByIDReq) Descriptor() ([]byte, []int) {
	return file_gradeclass_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteGradeClassByIDReq) GetGradeClassID() int64 {
	if x != nil {
		return x.GradeClassID
	}
	return 0
}

type GradeclassAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GradeclassAll) Reset() {
	*x = GradeclassAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gradeclass_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GradeclassAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeclassAll) ProtoMessage() {}

func (x *GradeclassAll) ProtoReflect() protoreflect.Message {
	mi := &file_gradeclass_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeclassAll.ProtoReflect.Descriptor instead.
func (*GradeclassAll) Descriptor() ([]byte, []int) {
	return file_gradeclass_proto_rawDescGZIP(), []int{9}
}

func (x *GradeclassAll) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GradeclassAll) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GradeclassAllResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GradeclassAll []*GradeclassAll `protobuf:"bytes,1,rep,name=gradeclassAll,proto3" json:"gradeclassAll,omitempty"`
}

func (x *GradeclassAllResp) Reset() {
	*x = GradeclassAllResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gradeclass_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GradeclassAllResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeclassAllResp) ProtoMessage() {}

func (x *GradeclassAllResp) ProtoReflect() protoreflect.Message {
	mi := &file_gradeclass_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeclassAllResp.ProtoReflect.Descriptor instead.
func (*GradeclassAllResp) Descriptor() ([]byte, []int) {
	return file_gradeclass_proto_rawDescGZIP(), []int{10}
}

func (x *GradeclassAllResp) GetGradeclassAll() []*GradeclassAll {
	if x != nil {
		return x.GradeclassAll
	}
	return nil
}

var File_gradeclass_proto protoreflect.FileDescriptor

var file_gradeclass_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x72, 0x61, 0x64, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x22, 0xa1, 0x02,
	0x0a, 0x0d, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x44, 0x61, 0x6f, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x6d, 0x61, 0x72,
	0x6b, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b,
	0x73, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x61,
	0x64, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x67, 0x72, 0x61, 0x64, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x7a, 0x7a, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x63, 0x6c, 0x61, 0x7a, 0x7a, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74,
	0x73, 0x22, 0x6e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x66, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2b, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x61,
	0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x44, 0x61, 0x6f, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x45, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x26, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x47, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49,
	0x44, 0x22, 0xa9, 0x02, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c,
	0x61, 0x73, 0x73, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x42, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x42, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x61, 0x64, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x67, 0x72, 0x61, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6c, 0x61, 0x7a, 0x7a, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x7a,
	0x7a, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x22, 0xb3, 0x01,
	0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x61, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x67, 0x72, 0x61, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x61,
	0x7a, 0x7a, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x7a, 0x7a, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x79, 0x49,
	0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42,
	0x79, 0x49, 0x44, 0x22, 0x94, 0x01, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x47, 0x72, 0x61, 0x64, 0x65,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x6d, 0x61,
	0x72, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x6d, 0x61, 0x72,
	0x6b, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x61, 0x64, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x67, 0x72, 0x61, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6c, 0x61, 0x7a, 0x7a, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6c, 0x61,
	0x7a, 0x7a, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x79, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x62, 0x79, 0x49, 0x44, 0x22, 0x3d, 0x0a, 0x17, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x42, 0x79,
	0x49, 0x44, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x0c, 0x67, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c,
	0x61, 0x73, 0x73, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x67, 0x72, 0x61,
	0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x44, 0x22, 0x33, 0x0a, 0x0d, 0x47, 0x72, 0x61,
	0x64, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x41, 0x6c, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4c,
	0x0a, 0x11, 0x47, 0x72, 0x61, 0x64, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x0d, 0x67, 0x72, 0x61, 0x64, 0x65, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x41, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x72, 0x61, 0x64, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x41, 0x6c, 0x6c, 0x52, 0x0d, 0x67,
	0x72, 0x61, 0x64, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x41, 0x6c, 0x6c, 0x32, 0xa9, 0x03, 0x0a,
	0x0a, 0x67, 0x72, 0x61, 0x64, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x3f, 0x0a, 0x0d, 0x67,
	0x72, 0x61, 0x64, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x41, 0x6c, 0x6c, 0x12, 0x17, 0x2e, 0x70,
	0x62, 0x2e, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x61, 0x64, 0x65,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3c, 0x0a, 0x0d,
	0x67, 0x65, 0x74, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x14, 0x2e,
	0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x61, 0x64,
	0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x48, 0x0a, 0x11, 0x67, 0x65,
	0x74, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x42, 0x79, 0x49, 0x44, 0x12,
	0x18, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x74, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x42, 0x79, 0x49, 0x44,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x44, 0x0a, 0x10, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72,
	0x61, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65,
	0x71, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x61, 0x64,
	0x64, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x14, 0x2e, 0x70, 0x62,
	0x2e, 0x41, 0x64, 0x64, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65,
	0x71, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x14, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x42, 0x79,
	0x49, 0x44, 0x12, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x72,
	0x61, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x1a,
	0x17, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x61, 0x64, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gradeclass_proto_rawDescOnce sync.Once
	file_gradeclass_proto_rawDescData = file_gradeclass_proto_rawDesc
)

func file_gradeclass_proto_rawDescGZIP() []byte {
	file_gradeclass_proto_rawDescOnce.Do(func() {
		file_gradeclass_proto_rawDescData = protoimpl.X.CompressGZIP(file_gradeclass_proto_rawDescData)
	})
	return file_gradeclass_proto_rawDescData
}

var file_gradeclass_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_gradeclass_proto_goTypes = []interface{}{
	(*GradeClassInterface)(nil),     // 0: pb.GradeClassInterface
	(*GradeClassDao)(nil),           // 1: pb.GradeClassDao
	(*GetGradeClassReq)(nil),        // 2: pb.GetGradeClassReq
	(*GetGradeClassResp)(nil),       // 3: pb.GetGradeClassResp
	(*GetGradeClassByIDReq)(nil),    // 4: pb.GetGradeClassByIDReq
	(*GetGradeClassByIDResp)(nil),   // 5: pb.GetGradeClassByIDResp
	(*UpdateGradeClassReq)(nil),     // 6: pb.UpdateGradeClassReq
	(*AddGradeClassReq)(nil),        // 7: pb.AddGradeClassReq
	(*DeleteGradeClassByIDReq)(nil), // 8: pb.DeleteGradeClassByIDReq
	(*GradeclassAll)(nil),           // 9: pb.GradeclassAll
	(*GradeclassAllResp)(nil),       // 10: pb.GradeclassAllResp
}
var file_gradeclass_proto_depIdxs = []int32{
	1,  // 0: pb.GetGradeClassResp.content:type_name -> pb.GradeClassDao
	9,  // 1: pb.GradeclassAllResp.gradeclassAll:type_name -> pb.GradeclassAll
	0,  // 2: pb.gradeclass.gradeclassAll:input_type -> pb.GradeClassInterface
	2,  // 3: pb.gradeclass.getGradeClass:input_type -> pb.GetGradeClassReq
	4,  // 4: pb.gradeclass.getGradeClassByID:input_type -> pb.GetGradeClassByIDReq
	6,  // 5: pb.gradeclass.updateGradeClass:input_type -> pb.UpdateGradeClassReq
	7,  // 6: pb.gradeclass.addGradeClass:input_type -> pb.AddGradeClassReq
	8,  // 7: pb.gradeclass.deleteGradeClassByID:input_type -> pb.DeleteGradeClassByIDReq
	10, // 8: pb.gradeclass.gradeclassAll:output_type -> pb.GradeclassAllResp
	3,  // 9: pb.gradeclass.getGradeClass:output_type -> pb.GetGradeClassResp
	5,  // 10: pb.gradeclass.getGradeClassByID:output_type -> pb.GetGradeClassByIDResp
	0,  // 11: pb.gradeclass.updateGradeClass:output_type -> pb.GradeClassInterface
	0,  // 12: pb.gradeclass.addGradeClass:output_type -> pb.GradeClassInterface
	0,  // 13: pb.gradeclass.deleteGradeClassByID:output_type -> pb.GradeClassInterface
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_gradeclass_proto_init() }
func file_gradeclass_proto_init() {
	if File_gradeclass_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gradeclass_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GradeClassInterface); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gradeclass_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GradeClassDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gradeclass_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGradeClassReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gradeclass_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGradeClassResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gradeclass_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGradeClassByIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gradeclass_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGradeClassByIDResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gradeclass_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGradeClassReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gradeclass_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGradeClassReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gradeclass_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGradeClassByIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gradeclass_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GradeclassAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gradeclass_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GradeclassAllResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gradeclass_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gradeclass_proto_goTypes,
		DependencyIndexes: file_gradeclass_proto_depIdxs,
		MessageInfos:      file_gradeclass_proto_msgTypes,
	}.Build()
	File_gradeclass_proto = out.File
	file_gradeclass_proto_rawDesc = nil
	file_gradeclass_proto_goTypes = nil
	file_gradeclass_proto_depIdxs = nil
}
